def sentence_probability(sentence):

    # PCFG probabilities
    np_probabilities = {
        "tom": 0.7,
        "ann": 0.3
    }

    vp_probabilities = {
        "sings": 0.4,
        "dances": 0.6
    }

    words = sentence.lower().split()

    # Sentence must contain exactly two words
    if len(words) != 2:
        return 0.0

    subject = words[0]
    verb = words[1]

    # Check whether words can be generated by grammar
    if subject not in np_probabilities:
        return 0.0

    if verb not in vp_probabilities:
        return 0.0

    # S -> NP VP has probability 1.0
    probability = (
        1.0
        * np_probabilities[subject]
        * vp_probabilities[verb]
    )

    return probability


# Main program
sentence = input("Enter a two-word sentence: ")

probability = sentence_probability(sentence)

print("\nOutput:")
print(f"Sentence Probability = {probability:.2f}")
